name: Push to sekar

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on:  self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup AWS CLIcccc
        run: |
          echo "heloo"
